Расчет целевых метрик
Byndyusoft/byndyusoft-ml-tools pull request #2
Opened 2023-03-28 11:17 UTC by Rinatich

2023-03-28 12:23 UTC, kanybekov requested changes

2023-03-28 12:23 UTC, kanybekov commented on src/Metrics/Dtos/MultiClassClassificationMetrics.cs
> +    public class MultiClassClassificationMetrics
документация?

2023-03-28 12:23 UTC, kanybekov commented on src/Metrics/Dtos/ClassificationResultWithConfidence.cs
> +    public class ClassificationResultWithConfidence : ClassificationResult
документация?

2023-03-28 12:23 UTC, kanybekov commented on src/Metrics/Helpers/ClassificationMetricsCalculatorHelper.cs
> +        public static ClassificationMetrics Calculate(
почему у калькуляторхелпера метод калькулейт?

2023-03-28 12:23 UTC, kanybekov commented on src/Metrics/Helpers/ClassificationMetricsCalculatorHelper.cs
> +        public static ClassificationMetrics Calculate(
Это калькулейтметрикс получается?

2023-03-28 12:23 UTC, kanybekov commented on src/Metrics/Helpers/ClassificationMetricsCalculatorHelper.cs
> +            var totalConfusionMatrixValueCounts = multiClassConfusionMatrixValueCounts.GetTotalCounts();
не понимаю эту строку
из каунтс получаем тотал каунтс? Это просто сумма всех?

2023-03-28 12:23 UTC, kanybekov commented on src/Metrics/Helpers/ClassificationMetricsCalculatorHelper.cs
> +            var sum = truePositiveCount + confusionMatrixValueCounts.GetCount(ConfusionMatrixValue.FalsePositive);
сум чего?

2023-03-28 12:23 UTC, kanybekov commented on src/Metrics/Helpers/ClassificationMetricsCalculatorHelper.cs
> +            var truePositiveCount = confusionMatrixValueCounts.GetCount(ConfusionMatrixValue.TruePositive);
тру позитив что

2023-03-28 12:23 UTC, kanybekov commented on src/Metrics/Helpers/ClassificationMetricsCalculatorHelper.cs
> +            var sum = truePositiveCount + confusionMatrixValueCounts.GetCount(ConfusionMatrixValue.FalseNegative);
сум чего

2023-03-28 12:23 UTC, kanybekov commented on src/Metrics/Helpers/ClassificationMetricsCalculatorHelper.cs
> +            var doubledDivisor = 2 * truePositiveCount +
название странное

2023-03-28 12:23 UTC, kanybekov commented on src/Metrics/Helpers/ConfusionMatrixValueCounts.cs
> +                throw new ArgumentException("Count must be non-negative", nameof(count));
а ноль тоже нон негатив? :)

2023-03-28 12:23 UTC, kanybekov commented on src/Metrics/Helpers/DouglasPeuckerInterpolation.cs
> +                var pointWithMaxDistance = points
вынести в приватный метод

2023-03-28 12:23 UTC, kanybekov commented on src/Metrics/Helpers/DouglasPeuckerInterpolation.cs
> +        ///     The min distance tolerance of points to return.
перевести не смог, порядок слов точно правильный?

2023-03-28 12:23 UTC, kanybekov commented on src/Metrics/Helpers/DouglasPeuckerInterpolation.cs
> +            if (maxPointCount < MinPoints || points.Length < maxPointCount)
сложное условие, можно ли на метод заменить

2023-03-28 12:23 UTC, kanybekov commented on src/Metrics/Helpers/DouglasPeuckerInterpolation.cs
> +            var next = segment.End + 1;
next что

2023-03-29 07:01 UTC, kanybekov approved these changes

2023-03-29 07:21 UTC, Alex-Grigorichev approved these changes

2023-03-29 09:19 UTC, maks-madasov approved these changes

2023-03-29 10:21 UTC, merged