Доработки precision recall curve
Byndyusoft/byndyusoft-ml-tools pull request #3
Opened 2023-03-31 11:26 UTC by Rinatich

- Убрал прямоугольную интерполяцию (она делала метрики оптимистическими)
- Убрал точки, где нельзя посчитать precision или recall
- Не возвращаются графики, если по ним нельзя рассчитать ни одной точки
- Добавил комментарии
- Сделал расчет AP по трапециям вместо прямоугольников
- Добавил пример в файл и тесты

2023-03-31 12:36 UTC, Alex-Grigorichev commented on src/Metrics/Helpers/PrecisionRecallCurveCalculatorHelper.cs
> +            var basesHalfSum = (currentDataPoint.Precision + previousDataPoint.Precision) / 2D;
не очень нравится название, но не могу придумать ничего более понятно

2023-03-31 12:39 UTC, Alex-Grigorichev requested changes

2023-03-31 12:39 UTC, Alex-Grigorichev commented on src/Metrics/Helpers/PrecisionRecallCurveCalculatorHelper.cs
> +            var resultDataPoints = new List<PrecisionRecallCurveDataPoint>(precisionValues.Count + 2);
не нравится result, предлагаю что-то типа curveDataPoints

2023-04-03 05:03 UTC, Rinatich commented on src/Metrics/Helpers/PrecisionRecallCurveCalculatorHelper.cs
> +            var resultDataPoints = new List<PrecisionRecallCurveDataPoint>(precisionValues.Count + 2);
++

2023-04-03 05:03 UTC, Rinatich commented on src/Metrics/Helpers/PrecisionRecallCurveCalculatorHelper.cs
> +            var basesHalfSum = (currentDataPoint.Precision + previousDataPoint.Precision) / 2D;
++

2023-04-03 05:06 UTC, Alex-Grigorichev approved these changes

2023-04-04 05:50 UTC, maks-madasov approved these changes

2023-04-04 06:00 UTC, kanybekov approved these changes
три замечания по неймингу, остальное все ок

2023-04-04 06:00 UTC, kanybekov commented on src/Metrics/Helpers/DouglasPeuckerInterpolation.cs
> +            if (maxPointCount < MinPoints)
Как будто не хватает уточнения к чему относится минпоинтс и макспоинткаунт.
Сейчас код в отрыве не смотрится, нужно все равно перелистывать к опрделению

2023-04-04 06:00 UTC, kanybekov commented on src/Metrics/Helpers/PrecisionRecallCurveCalculatorHelper.cs
> +            return trapezoidArea;
не бьется возвращаемое значение с названием метода

2023-04-04 06:00 UTC, kanybekov commented on src/Metrics/Helpers/PrecisionRecallCurveCalculatorHelper.cs
> +            var curveDataPoints = new List<PrecisionRecallCurveDataPoint>(precisionValues.Count + 2);
что такое 2?

2023-04-05 08:49 UTC, merged